services:
  app:
    build: .
    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tic-tac-toe-db
      SPRING_DATASOURCE_USERNAME: trumpecy
      SPRING_DATASOURCE_PASSWORD: trumpecy
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: trumpecy
      POSTGRES_PASSWORD: trumpecy
      POSTGRES_DB: tic-tac-toe-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data: